### ISSUE TITLE
add ultra sound relay

### ISSUE THREAD

**Issue by JustinDrake** [antonydenyer/flashbots-compose#3]
Consider adding the ultra sound sound [here](https://github.com/antonydenyer/flashbots-compose/blob/main/docker-compose.mainnet.yml#L24). It's a non-censoring relay, with more information at [relay.ultrasound.money](https://relay.ultrasound.money) :)

**Comment by antonydenyer** [comment]
The flashbots builder will either censor or it wont, there's no way to configure things on a per relay basis which is a little annoying. 

https://github.com/flashbots/builder/issues/40
